console.log('test');

// -> HELLO?

// -> IS ANYONE READING THIS?

// -> IF YOU'RE THERE, TYPE YES . . . . 

// -> GREAT! THIS IS DR. HIROSHI BENSON. I'M BEING HELD CAPTIVE.
//    I'M BEING	FORCED TO DIVULGE THE SECRETS TO MY ADVANCED SHAVE
//    TECHNOLOGY! MY GREATEST CREATION, HYDROBOT COULD SAVE ME BUT
//    HE'S INCOMPLETE. YOU NEED TO ENTER THE SECRET HYRDO LAIR,
//    FINISH HYDROBOT AND SAVE THE DAY. THERE'S AN ENTRANCE TO THE
//    LAIR THROUGH THIS ROOM. TO OPEN IT YOU MUST PUT THE HEADS IN
//    THE CORRECT ORDER ON THE TOP SHELF. THE ORDER IS... OH NO!
//    THEY'RE COMING.

// -> - - SIGNAL DISCONNECTED - -


var data = [
	"HELLO?",
	"IS ANYONE READING THIS?",
	"IF YOU'RE THERER, TYPE YES . . . ."
]


